# Generated by Django 3.0.5 on 2020-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=25, unique=True)),
                ('field_quantity', models.PositiveIntegerField()),
                ('field_randomize', models.PositiveIntegerField()),
            ],
        ),
    ]
